/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.core.io.Resource;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-12-26T14:49:35.566Z")

@Api(value = "q-paper", description = "the q-paper API")
public interface QPaperApi {

    @ApiOperation(value = "download file", nickname = "downloadFile", notes = "", response = Resource.class, tags={ "Q-Paper", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Resource.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 401, message = "user is unauthorised to make this request"),
        @ApiResponse(code = 404, message = "not found"),
        @ApiResponse(code = 408, message = "Request timeout"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/q-paper/download/{qpaperId}",
        produces = { "text/plain; charset=utf-8", "image/png", "image/gif", "image/jpeg", "application/pdf" }, 
        method = RequestMethod.GET)
    ResponseEntity<Resource> downloadFile(@ApiParam(value = "Question Paper Id",required=true) @PathVariable("qpaperId") Long qpaperId,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "userId", required = true) Long userId);


    @ApiOperation(value = "update form data", nickname = "updateQPaper", notes = "", tags={ "Q-Paper", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 401, message = "user is unauthorised to make this request"),
        @ApiResponse(code = 404, message = "not found"),
        @ApiResponse(code = 408, message = "Request timeout"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/q-paper/update/{qpaperId}",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateQPaper(@ApiParam(value = "",required=true) @PathVariable("qpaperId") Long qpaperId,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "userId", required = true) Long userId,@ApiParam(value = "doc name.", required=true) @RequestParam(value="DocName", required=true)  String docName,@ApiParam(value = "") @RequestParam(value="category", required=false)  String category,@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile uploadfile,@ApiParam(value = "") @RequestParam(value="tags", required=false)  String tags);


    @ApiOperation(value = "Add a question paper", nickname = "uploadQPaper", notes = "", tags={ "Q-Paper", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 401, message = "user is unauthorised to make this request"),
        @ApiResponse(code = 404, message = "not found"),
        @ApiResponse(code = 408, message = "Request timeout"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/q-paper/upload/{userId}",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.POST)
    ResponseEntity<Void> uploadQPaper(@ApiParam(value = "",required=true) @PathVariable("userId") Long userId,@ApiParam(value = "doc name.", required=true) @RequestParam(value="QPaperName", required=true)  String qpaperName,@ApiParam(value = "") @RequestParam(value="category", required=false)  String category,@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile uploadfile,@ApiParam(value = "") @RequestParam(value="tags", required=false)  String tags);

}
